### ISSUE TITLE
YouTube video on Landscape iPhone width bug - iOS7

### ISSUE THREAD

**Issue by teriu** [malsup/cycle2#361]
Seems to be a weird bug where the YouTube slide does not maintain the same aspect ratio as any image slides, the end result being that the YouTube slide maxes out at 320px wide.

![img_0202](https://f.cloud.github.com/assets/4244316/1596404/34e83c14-52fb-11e3-8d81-b3d339471d35.PNG)

**Comment by mallowtechdev** [comment]
I get the same issue on the iPad in portrait mode. The video size is fixed to 300px width and 150px height.
![cycle2-video-issue](https://cloud.githubusercontent.com/assets/2545137/4164195/b4231f48-34f1-11e4-99c8-817f702ac76c.png)

**Comment by rubaff** [comment]
Same here. I would love to use the lib and tried every possible CSS-fix. No luck. Any more ideas? If not I will have to use Owl Carousel.

**Comment by daniellelecomte** [comment]
Anyone ever find a solution to this one? Still an issue for me.
