### ISSUE TITLE
Carousel plugin: active class starts in wrong place

### ISSUE THREAD

**Issue by weshardee** [malsup/cycle2#77]
The active class isn't applied consistently. It starts in the wrong place for the first iteration through the slides, and then jumps to the beginning of the list (where I assume it should be the whole time). Limiting the number of slides seems to fix the issue.

Example: http://codepen.io/weshardee/pen/oglec

**Comment by weshardee** [comment]
Perhaps it would be best to have all instances of the active slide have the active class, rather than just the one. Look at my example for how the styling that's applied to the active slide "jumps" every time the first slide is reached again.

**Comment by malsup** [comment]
I thought I fixed this.  Did you test with latest?  version: 20130108

**Comment by weshardee** [comment]
I just tested with version 20130108, and it behaves pretty much the same as before (except now there's no sentinel slide to keep the slideshow from collapsing). 

The 'active' slide is still not the first visible slide in the carousel, and at some points there appears to be no active slide at all. 

http://codepen.io/weshardee/pen/oglec

**Comment by weshardee** [comment]
In my example the slideshow starts at 'left: 0', but once it goes through all the slides, it switches to using 'left: -420px' as the starting position. So during the first iteration, the active slide is in the middle visually.

**Comment by weshardee** [comment]
Not sure if this is a new issue, or related, but this demo is now broken and won't advance past slide 5: http://jquery.malsup.com/cycle2/demo/caro-pager.php

**Comment by ornj** [comment]
I'm seeing behavior that is consistant with @weshardee using version 20130108 and jQuery 1.9.

If `cycle-carousel-visible` is given a value then the active slide is properly set. If not the carousel needs to go through a full iteration before it begins to add the class correctly.

http://jsfiddle.net/4wrJA/

**Comment by ornj** [comment]
I've also noticed that when the carousel is transitioning back to having the first slide at the beginning of the container  it delays adding the active class until after the animation is complete.

**Comment by scottbabcock** [comment]
This bug still exists as of version 20141007, but the workaround of setting <code>cycle-carousel-visible</code> still works.

**Comment by kdobryansky** [comment]
I used this solution:
first, hook on update-view event:
`$('#cycle_container').on('cycle-update-view', function( event, optionHash, slideOptionsHash, currentSlideEl ) {})`

then, inside event function I get current selected element, and appended `cycle-slide-active` class to all element clones (i used unique class for element), just like weshardee said.

That's it. Now, all active cycle elements has active class.
